// Named HTML entities mapping
export const namedEntities: { [key: string]: string } = {
  // Basic entities
  'lt': '<',
  'gt': '>',
  'amp': '&',
  'quot': '"',
  'apos': "'",
  
  // Common punctuation
  'excl': '!',
  'num': '#',
  'dollar': '$',
  'percnt': '%',
  'lpar': '(',
  'rpar': ')',
  'ast': '*',
  'plus': '+',
  'comma': ',',
  'period': '.',
  'sol': '/',
  'colon': ':',
  'semi': ';',
  'equals': '=',
  'quest': '?',
  'commat': '@',
  'lsqb': '[',
  'rsqb': ']',
  'bsol': '\\',
  'Hat': '^',
  'lowbar': '_',
  'grave': '`',
  'lbrace': '{',
  'verbar': '|',
  'rbrace': '}',
  'tilde': '~',
  
  // Common symbols
  'copy': '©',
  'reg': '®',
  'trade': '™',
  'euro': '€',
  'pound': '£',
  'yen': '¥',
  'cent': '¢',
  'sect': '§',
  'para': '¶',
  'deg': '°',
  'plusmn': '±',
  'times': '×',
  'divide': '÷',
  'frac12': '½',
  'frac14': '¼',
  'frac34': '¾',
  'sup1': '¹',
  'sup2': '²',
  'sup3': '³',
  'middot': '·',
  'ndash': '–',
  'mdash': '—',
  'hellip': '…',
  'prime': '′',
  'Prime': '″',
  'lsquo': '\u2018',
  'rsquo': '\u2019',
  'ldquo': '\u201c',
  'rdquo': '\u201d',
  'bull': '•',
  'dagger': '†',
  'Dagger': '‡',
  'permil': '‰',
  
  // Accented characters
  'Agrave': 'À',
  'Aacute': 'Á',
  'Acirc': 'Â',
  'Atilde': 'Ã',
  'Auml': 'Ä',
  'Aring': 'Å',
  'AElig': 'Æ',
  'Ccedil': 'Ç',
  'Egrave': 'È',
  'Eacute': 'É',
  'Ecirc': 'Ê',
  'Euml': 'Ë',
  'Igrave': 'Ì',
  'Iacute': 'Í',
  'Icirc': 'Î',
  'Iuml': 'Ï',
  'ETH': 'Ð',
  'Ntilde': 'Ñ',
  'Ograve': 'Ò',
  'Oacute': 'Ó',
  'Ocirc': 'Ô',
  'Otilde': 'Õ',
  'Ouml': 'Ö',
  'Oslash': 'Ø',
  'Ugrave': 'Ù',
  'Uacute': 'Ú',
  'Ucirc': 'Û',
  'Uuml': 'Ü',
  'Yacute': 'Ý',
  'THORN': 'Þ',
  'szlig': 'ß',
  'agrave': 'à',
  'aacute': 'á',
  'acirc': 'â',
  'atilde': 'ã',
  'auml': 'ä',
  'aring': 'å',
  'aelig': 'æ',
  'ccedil': 'ç',
  'egrave': 'è',
  'eacute': 'é',
  'ecirc': 'ê',
  'euml': 'ë',
  'igrave': 'ì',
  'iacute': 'í',
  'icirc': 'î',
  'iuml': 'ï',
  'eth': 'ð',
  'ntilde': 'ñ',
  'ograve': 'ò',
  'oacute': 'ó',
  'ocirc': 'ô',
  'otilde': 'õ',
  'ouml': 'ö',
  'oslash': 'ø',
  'ugrave': 'ù',
  'uacute': 'ú',
  'ucirc': 'û',
  'uuml': 'ü',
  'yacute': 'ý',
  'thorn': 'þ',
  'yuml': 'ÿ',
  
  // Math symbols
  'forall': '∀',
  'part': '∂',
  'exist': '∃',
  'empty': '∅',
  'nabla': '∇',
  'isin': '∈',
  'notin': '∉',
  'ni': '∋',
  'prod': '∏',
  'sum': '∑',
  'minus': '−',
  'lowast': '∗',
  'radic': '√',
  'prop': '∝',
  'infin': '∞',
  'ang': '∠',
  'and': '∧',
  'or': '∨',
  'cap': '∩',
  'cup': '∪',
  'int': '∫',
  'there4': '∴',
  'sim': '∼',
  'cong': '≅',
  'asymp': '≈',
  'ne': '≠',
  'equiv': '≡',
  'le': '≤',
  'ge': '≥',
  'sub': '⊂',
  'sup': '⊃',
  'nsub': '⊄',
  'sube': '⊆',
  'supe': '⊇',
  'oplus': '⊕',
  'otimes': '⊗',
  'perp': '⊥',
  'sdot': '⋅',
  
  // Greek letters
  'Alpha': 'Α',
  'Beta': 'Β',
  'Gamma': 'Γ',
  'Delta': 'Δ',
  'Epsilon': 'Ε',
  'Zeta': 'Ζ',
  'Eta': 'Η',
  'Theta': 'Θ',
  'Iota': 'Ι',
  'Kappa': 'Κ',
  'Lambda': 'Λ',
  'Mu': 'Μ',
  'Nu': 'Ν',
  'Xi': 'Ξ',
  'Omicron': 'Ο',
  'Pi': 'Π',
  'Rho': 'Ρ',
  'Sigma': 'Σ',
  'Tau': 'Τ',
  'Upsilon': 'Υ',
  'Phi': 'Φ',
  'Chi': 'Χ',
  'Psi': 'Ψ',
  'Omega': 'Ω',
  'alpha': 'α',
  'beta': 'β',
  'gamma': 'γ',
  'delta': 'δ',
  'epsilon': 'ε',
  'zeta': 'ζ',
  'eta': 'η',
  'theta': 'θ',
  'iota': 'ι',
  'kappa': 'κ',
  'lambda': 'λ',
  'mu': 'μ',
  'nu': 'ν',
  'xi': 'ξ',
  'omicron': 'ο',
  'pi': 'π',
  'rho': 'ρ',
  'sigma': 'σ',
  'tau': 'τ',
  'upsilon': 'υ',
  'phi': 'φ',
  'chi': 'χ',
  'psi': 'ψ',
  'omega': 'ω',
  'thetasym': 'ϑ',
  'upsih': 'ϒ',
  'piv': 'ϖ',
};

// Reverse mapping for unescaping
export const reverseNamedEntities: { [key: string]: string } = {};
Object.entries(namedEntities).forEach(([name, char]) => {
  reverseNamedEntities[char] = name;
});

export const escapeHtml = (input: string): string => {
  return input
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;'); // Use numeric for apostrophe
};

export const unescapeHtml = (input: string): string => {
  return input
    // Handle numeric entities (#65; and #x41;)
    .replace(/&#(\d+);/g, (match, dec) => {
      const code = parseInt(dec, 10);
      return String.fromCharCode(code);
    })
    .replace(/&#x([0-9a-fA-F]+);/g, (match, hex) => {
      const code = parseInt(hex, 16);
      return String.fromCharCode(code);
    })
    // Handle named entities
    .replace(/&([a-zA-Z]+);/g, (match, name) => {
      return namedEntities[name] || match;
    });
};
