import { CountryData } from './types';

// Helper to format digits into groups
function groupDigits(digits: string, groups: number[]): string {
  let result = '';
  let index = 0;
  for (const size of groups) {
    if (index >= digits.length) break;
    if (index > 0) result += ' ';
    result += digits.slice(index, index + size);
    index += size;
  }
  if (index < digits.length) {
    result += ' ' + digits.slice(index);
  }
  return result;
}

export const COUNTRIES: Record<string, CountryData> = {
  US: {
    name: 'United States',
    dialCode: '1',
    iso2: 'US',
    iso3: 'USA',
    minLength: 10,
    maxLength: 10,
    formatNational: (digits) => `(${digits.slice(0, 3)}) ${digits.slice(3, 6)}-${digits.slice(6)}`,
    formatInternational: (digits, dialCode) => `+${dialCode} ${digits.slice(0, 3)} ${digits.slice(3, 6)} ${digits.slice(6)}`,
  },
  CA: {
    name: 'Canada',
    dialCode: '1',
    iso2: 'CA',
    iso3: 'CAN',
    minLength: 10,
    maxLength: 10,
    formatNational: (digits) => `(${digits.slice(0, 3)}) ${digits.slice(3, 6)}-${digits.slice(6)}`,
    formatInternational: (digits, dialCode) => `+${dialCode} ${digits.slice(0, 3)} ${digits.slice(3, 6)} ${digits.slice(6)}`,
  },
  GB: {
    name: 'United Kingdom',
    dialCode: '44',
    iso2: 'GB',
    iso3: 'GBR',
    minLength: 10,
    maxLength: 10,
    formatNational: (digits) => `${digits.slice(0, 4)} ${digits.slice(4, 7)} ${digits.slice(7)}`,
    formatInternational: (digits, dialCode) => `+${dialCode} ${digits.slice(0, 4)} ${digits.slice(4, 7)} ${digits.slice(7)}`,
  },
  NG: {
    name: 'Nigeria',
    dialCode: '234',
    iso2: 'NG',
    iso3: 'NGA',
    minLength: 10,
    maxLength: 10,
    formatNational: (digits) => `${digits.slice(0, 3)} ${digits.slice(3, 6)} ${digits.slice(6)}`,
    formatInternational: (digits, dialCode) => `+${dialCode} ${digits.slice(0, 3)} ${digits.slice(3, 6)} ${digits.slice(6)}`,
  },
  IN: {
    name: 'India',
    dialCode: '91',
    iso2: 'IN',
    iso3: 'IND',
    minLength: 10,
    maxLength: 10,
    formatNational: (digits) => `${digits.slice(0, 5)} ${digits.slice(5)}`,
    formatInternational: (digits, dialCode) => `+${dialCode} ${digits.slice(0, 5)} ${digits.slice(5)}`,
  },
  DE: {
    name: 'Germany',
    dialCode: '49',
    iso2: 'DE',
    iso3: 'DEU',
    minLength: 10,
    maxLength: 11,
    formatNational: (digits) => groupDigits(digits, [4, 3, 4]),
    formatInternational: (digits, dialCode) => `+${dialCode} ${groupDigits(digits, [4, 3, 4])}`,
  },
  FR: {
    name: 'France',
    dialCode: '33',
    iso2: 'FR',
    iso3: 'FRA',
    minLength: 9,
    maxLength: 9,
    formatNational: (digits) => groupDigits(digits, [2, 2, 2, 2, 1]),
    formatInternational: (digits, dialCode) => `+${dialCode} ${groupDigits(digits, [1, 2, 2, 2, 2])}`,
  },
  BR: {
    name: 'Brazil',
    dialCode: '55',
    iso2: 'BR',
    iso3: 'BRA',
    minLength: 11,
    maxLength: 11,
    formatNational: (digits) => `(${digits.slice(0, 2)}) ${digits.slice(2, 7)}-${digits.slice(7)}`,
    formatInternational: (digits, dialCode) => `+${dialCode} ${digits.slice(0, 2)} ${digits.slice(2, 7)} ${digits.slice(7)}`,
  },
  AU: {
    name: 'Australia',
    dialCode: '61',
    iso2: 'AU',
    iso3: 'AUS',
    minLength: 9,
    maxLength: 9,
    formatNational: (digits) => `${digits.slice(0, 1)} ${digits.slice(1, 5)} ${digits.slice(5)}`,
    formatInternational: (digits, dialCode) => `+${dialCode} ${digits.slice(0, 1)} ${digits.slice(1, 5)} ${digits.slice(5)}`,
  },
  JP: {
    name: 'Japan',
    dialCode: '81',
    iso2: 'JP',
    iso3: 'JPN',
    minLength: 10,
    maxLength: 10,
    formatNational: (digits) => `${digits.slice(0, 3)}-${digits.slice(3, 7)}-${digits.slice(7)}`,
    formatInternational: (digits, dialCode) => `+${dialCode} ${digits.slice(0, 3)} ${digits.slice(3, 7)} ${digits.slice(7)}`,
  },
  CN: {
    name: 'China',
    dialCode: '86',
    iso2: 'CN',
    iso3: 'CHN',
    minLength: 11,
    maxLength: 11,
    formatNational: (digits) => `${digits.slice(0, 3)} ${digits.slice(3, 7)} ${digits.slice(7)}`,
    formatInternational: (digits, dialCode) => `+${dialCode} ${digits.slice(0, 3)} ${digits.slice(3, 7)} ${digits.slice(7)}`,
  },
  RU: {
    name: 'Russia',
    dialCode: '7',
    iso2: 'RU',
    iso3: 'RUS',
    minLength: 10,
    maxLength: 10,
    formatNational: (digits) => `(${digits.slice(0, 3)}) ${digits.slice(3, 6)}-${digits.slice(6, 8)}-${digits.slice(8)}`,
    formatInternational: (digits, dialCode) => `+${dialCode} ${digits.slice(0, 3)} ${digits.slice(3, 6)}-${digits.slice(6, 8)}-${digits.slice(8)}`,
  },
  ZA: {
    name: 'South Africa',
    dialCode: '27',
    iso2: 'ZA',
    iso3: 'ZAF',
    minLength: 9,
    maxLength: 9,
    formatNational: (digits) => `${digits.slice(0, 2)} ${digits.slice(2, 5)} ${digits.slice(5)}`,
    formatInternational: (digits, dialCode) => `+${dialCode} ${digits.slice(0, 2)} ${digits.slice(2, 5)} ${digits.slice(5)}`,
  },
  MX: {
    name: 'Mexico',
    dialCode: '52',
    iso2: 'MX',
    iso3: 'MEX',
    minLength: 10,
    maxLength: 10,
    formatNational: (digits) => `${digits.slice(0, 2)} ${digits.slice(2, 6)} ${digits.slice(6)}`,
    formatInternational: (digits, dialCode) => `+${dialCode} ${digits.slice(0, 2)} ${digits.slice(2, 6)} ${digits.slice(6)}`,
  },
  IT: {
    name: 'Italy',
    dialCode: '39',
    iso2: 'IT',
    iso3: 'ITA',
    minLength: 10,
    maxLength: 10,
    formatNational: (digits) => `${digits.slice(0, 3)} ${digits.slice(3, 6)} ${digits.slice(6)}`,
    formatInternational: (digits, dialCode) => `+${dialCode} ${digits.slice(0, 3)} ${digits.slice(3, 6)} ${digits.slice(6)}`,
  },
  ES: {
    name: 'Spain',
    dialCode: '34',
    iso2: 'ES',
    iso3: 'ESP',
    minLength: 9,
    maxLength: 9,
    formatNational: (digits) => `${digits.slice(0, 3)} ${digits.slice(3, 5)} ${digits.slice(5, 7)} ${digits.slice(7)}`,
    formatInternational: (digits, dialCode) => `+${dialCode} ${digits.slice(0, 3)} ${digits.slice(3, 5)} ${digits.slice(5, 7)} ${digits.slice(7)}`,
  },
  KE: {
    name: 'Kenya',
    dialCode: '254',
    iso2: 'KE',
    iso3: 'KEN',
    minLength: 9,
    maxLength: 9,
    formatNational: (digits) => `${digits.slice(0, 3)} ${digits.slice(3, 6)} ${digits.slice(6)}`,
    formatInternational: (digits, dialCode) => `+${dialCode} ${digits.slice(0, 3)} ${digits.slice(3, 6)} ${digits.slice(6)}`,
  },
  GH: {
    name: 'Ghana',
    dialCode: '233',
    iso2: 'GH',
    iso3: 'GHA',
    minLength: 9,
    maxLength: 9,
    formatNational: (digits) => `${digits.slice(0, 3)} ${digits.slice(3, 6)} ${digits.slice(6)}`,
    formatInternational: (digits, dialCode) => `+${dialCode} ${digits.slice(0, 3)} ${digits.slice(3, 6)} ${digits.slice(6)}`,
  },
  EG: {
    name: 'Egypt',
    dialCode: '20',
    iso2: 'EG',
    iso3: 'EGY',
    minLength: 10,
    maxLength: 10,
    formatNational: (digits) => `${digits.slice(0, 3)} ${digits.slice(3, 7)} ${digits.slice(7)}`,
    formatInternational: (digits, dialCode) => `+${dialCode} ${digits.slice(0, 3)} ${digits.slice(3, 7)} ${digits.slice(7)}`,
  },
  PH: {
    name: 'Philippines',
    dialCode: '63',
    iso2: 'PH',
    iso3: 'PHL',
    minLength: 10,
    maxLength: 10,
    formatNational: (digits) => `${digits.slice(0, 3)} ${digits.slice(3, 6)} ${digits.slice(6)}`,
    formatInternational: (digits, dialCode) => `+${dialCode} ${digits.slice(0, 3)} ${digits.slice(3, 6)} ${digits.slice(6)}`,
  },
  KR: {
    name: 'South Korea',
    dialCode: '82',
    iso2: 'KR',
    iso3: 'KOR',
    minLength: 10,
    maxLength: 10,
    formatNational: (digits) => `${digits.slice(0, 2)}-${digits.slice(2, 6)}-${digits.slice(6)}`,
    formatInternational: (digits, dialCode) => `+${dialCode} ${digits.slice(0, 2)} ${digits.slice(2, 6)} ${digits.slice(6)}`,
  },
  ID: {
    name: 'Indonesia',
    dialCode: '62',
    iso2: 'ID',
    iso3: 'IDN',
    minLength: 10,
    maxLength: 12,
    formatNational: (digits) => groupDigits(digits, [3, 4, 4]),
    formatInternational: (digits, dialCode) => `+${dialCode} ${groupDigits(digits, [3, 4, 4])}`,
  },
  PK: {
    name: 'Pakistan',
    dialCode: '92',
    iso2: 'PK',
    iso3: 'PAK',
    minLength: 10,
    maxLength: 10,
    formatNational: (digits) => `${digits.slice(0, 3)} ${digits.slice(3, 7)} ${digits.slice(7)}`,
    formatInternational: (digits, dialCode) => `+${dialCode} ${digits.slice(0, 3)} ${digits.slice(3, 7)} ${digits.slice(7)}`,
  },
  BD: {
    name: 'Bangladesh',
    dialCode: '880',
    iso2: 'BD',
    iso3: 'BGD',
    minLength: 10,
    maxLength: 10,
    formatNational: (digits) => `${digits.slice(0, 4)} ${digits.slice(4, 7)} ${digits.slice(7)}`,
    formatInternational: (digits, dialCode) => `+${dialCode} ${digits.slice(0, 4)} ${digits.slice(4, 7)} ${digits.slice(7)}`,
  },
  TR: {
    name: 'Turkey',
    dialCode: '90',
    iso2: 'TR',
    iso3: 'TUR',
    minLength: 10,
    maxLength: 10,
    formatNational: (digits) => `(${digits.slice(0, 3)}) ${digits.slice(3, 6)} ${digits.slice(6, 8)} ${digits.slice(8)}`,
    formatInternational: (digits, dialCode) => `+${dialCode} ${digits.slice(0, 3)} ${digits.slice(3, 6)} ${digits.slice(6, 8)} ${digits.slice(8)}`,
  },
};

// Dial code to country mapping for detection
export const DIAL_CODE_MAP: Record<string, string[]> = {
  '1': ['US', 'CA'],
  '7': ['RU'],
  '20': ['EG'],
  '27': ['ZA'],
  '33': ['FR'],
  '34': ['ES'],
  '39': ['IT'],
  '44': ['GB'],
  '49': ['DE'],
  '52': ['MX'],
  '55': ['BR'],
  '61': ['AU'],
  '62': ['ID'],
  '63': ['PH'],
  '65': [], // Singapore not in our 20, but reserved
  '81': ['JP'],
  '82': ['KR'],
  '86': ['CN'],
  '91': ['IN'],
  '92': ['PK'],
  '234': ['NG'],
  '233': ['GH'],
  '254': ['KE'],
  '880': ['BD'],
  '90': ['TR'],
};

// Sorted by length descending for greedy matching
export const DIAL_CODES_SORTED = Object.keys(DIAL_CODE_MAP).sort((a, b) => b.length - a.length);