import type { FeaturedStream } from "./types";

// Realistic mock creators roster for StreamFi
export const mockCreators: FeaturedStream[] = [
  {
    creator_id: "creator_101",
    creator_username: "gaming_guru",
    creator_display_name: 'Alex "The Guru" Chen',
    stream_id: "stream_101_001",
    stream_title: "VALORANT Tournament Finals - Live Commentary",
    reason: "Top performer in this week's competitive gaming circuit",
    category: "Gaming",
    thumbnail_url: "https://cdn.streamfi.com/thumbnails/valorant-tournament.jpg",
    viewer_count: 12500,
    is_live: true,
  },
  {
    creator_id: "creator_102",
    creator_username: "music_maestro",
    creator_display_name: "Sarah Williams",
    stream_id: "stream_102_001",
    stream_title: "Acoustic Guitar Live Session - Original Compositions",
    reason: "Exceptional musical talent with high audience engagement",
    category: "Music",
    thumbnail_url: "https://cdn.streamfi.com/thumbnails/acoustic-session.jpg",
    viewer_count: 8200,
    is_live: true,
  },
  {
    creator_id: "creator_103",
    creator_username: "tech_talk",
    creator_display_name: "Marcus Rodriguez",
    stream_id: "stream_103_001",
    stream_title: "Building a Modern Web App with Next.js 14",
    reason: "Educational content with clear explanations and live coding",
    category: "Technology",
    thumbnail_url: "https://cdn.streamfi.com/thumbnails/nextjs-tutorial.jpg",
    viewer_count: 5600,
    is_live: true,
  },
  {
    creator_id: "creator_104",
    creator_username: "art_streamer",
    creator_display_name: 'Jamie "Sketch" Patel',
    stream_id: "stream_104_001",
    stream_title: "Digital Portrait Painting - From Sketch to Final",
    reason: "Stunning visual art with interactive viewer suggestions",
    category: "Art",
    thumbnail_url: "https://cdn.streamfi.com/thumbnails/digital-portrait.jpg",
    viewer_count: 4300,
    is_live: true,
  },
  {
    creator_id: "creator_105",
    creator_username: "fitness_coach",
    creator_display_name: "Coach Taylor Reed",
    stream_id: "stream_105_001",
    stream_title: "HIIT Workout Session - All Levels Welcome",
    reason: "High-energy fitness stream with community participation",
    category: "Fitness",
    thumbnail_url: "https://cdn.streamfi.com/thumbnails/hiit-workout.jpg",
    viewer_count: 3100,
    is_live: true,
  },
  {
    creator_id: "creator_106",
    creator_username: "cooking_with_joy",
    creator_display_name: 'Joy "SpiceMaster" Zhang',
    stream_id: "stream_106_001",
    stream_title: "Authentic Thai Curry - Step by Step Cooking",
    reason: "Exceptional culinary content with detailed explanations",
    category: "Cooking",
    thumbnail_url: "https://cdn.streamfi.com/thumbnails/thai-curry.jpg",
    viewer_count: 2900,
    is_live: true,
  },
  {
    creator_id: "creator_107",
    creator_username: "travel_vlogs",
    creator_display_name: 'Emma "Wanderlust" Thompson',
    stream_id: "stream_107_001",
    stream_title: "Virtual Tour of Tokyo's Hidden Gems",
    reason: "Immersive travel experience with live Q&A",
    category: "Travel",
    thumbnail_url: "https://cdn.streamfi.com/thumbnails/tokyo-tour.jpg",
    viewer_count: 2700,
    is_live: true,
  },
  {
    creator_id: "creator_108",
    creator_username: "science_explained",
    creator_display_name: "Dr. Benjamin Carter",
    stream_id: "stream_108_001",
    stream_title: "Quantum Mechanics for Beginners - Live Lecture",
    reason: "Complex topics made accessible with interactive demos",
    category: "Education",
    thumbnail_url: "https://cdn.streamfi.com/thumbnails/quantum-physics.jpg",
    viewer_count: 4100,
    is_live: true,
  },
  {
    creator_id: "creator_109",
    creator_username: "comedy_central",
    creator_display_name: 'Mike "Laughs" Johnson',
    stream_id: "stream_109_001",
    stream_title: "Improv Comedy Hour - Audience Suggestions Welcome",
    reason: "Hilarious entertainment with high viewer interaction",
    category: "Comedy",
    thumbnail_url: "https://cdn.streamfi.com/thumbnails/improv-comedy.jpg",
    viewer_count: 6800,
    is_live: true,
  },
  {
    creator_id: "creator_110",
    creator_username: "book_club_live",
    creator_display_name: 'Claire "Reader" Bennett',
    stream_id: "stream_110_001",
    stream_title: "Book Club Discussion - Sci-Fi Classics Edition",
    reason: "Intellectual discussion with active community participation",
    category: "Books",
    thumbnail_url: "https://cdn.streamfi.com/thumbnails/book-club.jpg",
    viewer_count: 1900,
    is_live: true,
  },
];

// Helper to get number of creators
export const totalCreators = mockCreators.length;