export const TAG_KEYWORDS: Record<string, string[]> = {
  gaming: [
    "game", "gaming", "play", "player", "fps", "rpg", "mmo", "moba",
    "battle", "boss", "raid", "level", "rank", "competitive", "esports",
    "stream", "twitch", "controller", "keyboard", "mouse", "gpu", "pc",
    "console", "playstation", "xbox", "nintendo", "steam", "valorant",
    "fortnite", "league", "minecraft", "apex", "cod", "overwatch",
    "destiny", "diablo", "wow", "ffxiv", "genshin", "roblox",
  ],
  music: [
    "music", "song", "track", "album", "artist", "band", "concert",
    "live", "performance", "dj", "remix", "beat", "rap", "hip hop",
    "rock", "pop", "edm", "techno", "bass", "guitar", "piano",
    "vocal", "sing", "karaoke", "playlist", "vinyl", "studio",
    "producer", "beats", "melody", "rhythm",
  ],
  irl: [
    "irl", "vlog", "daily", "life", "travel", "food", "cook", "cooking",
    "restaurant", "eat", "mukbang", "outdoor", "adventure", "city",
    "walk", "explore", "nature", "beach", "mountain", "camp",
    "fitness", "gym", "workout", "yoga", "pet", "dog", "cat",
    "unboxing", "haul", "fashion", "style",
  ],
  crypto: [
    "crypto", "bitcoin", "btc", "ethereum", "eth", "solana", "sol",
    "stellar", "xlm", "defi", "nft", "web3", "blockchain", "token",
    "wallet", "mining", "staking", "yield", "liquidity", "swap",
    "airdrop", "meme", "altcoin", "trading", "chart", "bull", "bear",
    "hodl", "moon", "pump",
  ],
  creative: [
    "art", "draw", "paint", "design", "creative", "illustration",
    "digital", "photoshop", "blender", "3d", "model", "animation",
    "manga", "comic", "sketch", "canvas", "color", "pixel",
    "timelapse", "speedpaint", "tutorial", "howto", "diy", "craft",
    "make", "build", "woodworking", "sew", "knit",
  ],
  sports: [
    "sport", "football", "soccer", "basketball", "baseball", "tennis",
    "golf", "mma", "ufc", "boxing", "wrestling", "f1", "racing",
    "nfl", "nba", "mlb", "nhl", "olympics", "world cup", "championship",
    "tournament", "league", "match", "game day", "highlight",
    "replay", "analysis", "draft",
  ],
  tech: [
    "tech", "technology", "code", "coding", "programming", "developer",
    "software", "hardware", "ai", "machine learning", "robot",
    "hack", "cyber", "security", "linux", "mac", "windows",
    "phone", "iphone", "android", "app", "review", "unbox",
    "setup", "desk", "monitor", "keyboard", "usb",
  ],
  just_chatting: [
    "chat", "talk", "discussion", "debate", "q&a", "ama", "story",
    "rant", "opinion", "news", "react", "reaction", "funny",
    "meme", "comedy", "joke", "laugh", "chill", "hangout",
    "podcast", "interview", "collab", "guest",
  ],
};
