export type ParagraphStyle = "technical" | "casual" | "formal" | "news";

const subjects: Record<ParagraphStyle, string[]> = {
  technical: [
    "The service gateway",
    "A typed event stream",
    "The cache layer",
    "Each deployment pipeline",
    "The telemetry collector",
    "A background worker",
    "The schema validator",
    "Every API boundary",
    "The query planner",
    "A resilient job queue",
    "The encryption module",
    "Each container image",
    "The feature flag system",
    "A distributed lock",
    "The metrics dashboard",
    "Every websocket shard",
    "The storage adapter",
    "A rate limiter",
    "The migration runner",
    "Each integration test",
  ],
  casual: [
    "The morning playlist",
    "A quick coffee break",
    "The group chat",
    "Every weekend plan",
    "The tiny kitchen table",
    "A rainy walk",
    "The borrowed hoodie",
    "Each movie night",
    "The late bus",
    "A fresh notebook",
    "The neighborhood bakery",
    "Every phone reminder",
    "The sleepy elevator",
    "A shared umbrella",
    "The open window",
    "Each dinner idea",
    "The messy desk",
    "A favorite podcast",
    "The corner store",
    "Every small errand",
  ],
  formal: [
    "The committee",
    "A comprehensive review",
    "The annual report",
    "Each department",
    "The appointed panel",
    "A revised procedure",
    "The governing board",
    "Every submitted proposal",
    "The institutional policy",
    "A formal assessment",
    "The executive office",
    "Each participating member",
    "The advisory council",
    "A documented finding",
    "The compliance program",
    "Every official notice",
    "The strategic framework",
    "A measured response",
    "The public record",
    "Each administrative unit",
  ],
  news: [
    "City officials",
    "The transport agency",
    "Local businesses",
    "Researchers",
    "The mayor's office",
    "Community organizers",
    "A regional hospital",
    "The school district",
    "Market analysts",
    "Emergency crews",
    "The election board",
    "A federal judge",
    "State regulators",
    "The weather service",
    "Union leaders",
    "Public health teams",
    "The finance ministry",
    "A technology firm",
    "Residents",
    "The council",
  ],
};

const predicates: Record<ParagraphStyle, string[]> = {
  technical: [
    "records structured traces before forwarding requests to downstream services.",
    "uses bounded retries to reduce transient failures during peak traffic.",
    "normalizes incoming payloads before validation rules are evaluated.",
    "publishes latency histograms so regressions are visible within minutes.",
    "keeps configuration isolated from runtime state to simplify rollbacks.",
  ],
  casual: [
    "turned into the kind of story everyone retold by dinner.",
    "made the whole afternoon feel easier than anyone expected.",
    "started with a tiny delay and ended with a surprisingly good laugh.",
    "left just enough time for one more stop on the way home.",
    "felt simple, useful, and a little brighter than yesterday.",
  ],
  formal: [
    "will remain subject to periodic evaluation under the approved guidelines.",
    "requires clear documentation before implementation may proceed.",
    "was adopted after consultation with the relevant stakeholders.",
    "establishes a consistent basis for future decisions and public reporting.",
    "reflects the standards set out in the current operating mandate.",
  ],
  news: [
    "said the change will take effect next month after final approval.",
    "reported higher demand as residents adjusted to the new schedule.",
    "confirmed that an investigation remains active and no further details were released.",
    "announced new funding aimed at improving services across the region.",
    "met Tuesday to discuss the impact of recent policy changes.",
  ],
};

function buildStyleCorpus(style: ParagraphStyle): string[] {
  return subjects[style].flatMap((subject) =>
    predicates[style].map((predicate) => `${subject} ${predicate}`),
  );
}

export const corpus: Record<ParagraphStyle, string[]> = {
  technical: buildStyleCorpus("technical"),
  casual: buildStyleCorpus("casual"),
  formal: buildStyleCorpus("formal"),
  news: buildStyleCorpus("news"),
};

export const styles = Object.keys(corpus) as ParagraphStyle[];
